;;; hubi-configure.el --- Configuration interface for hubi -*- lexical-binding: t -*-

;; Copyright (C) 2025 Alex Bennée

;; Author: Alex Bennée <alex@bennee.com>

;;; Commentary:

;; This provides the configuration interface for hubi, allowing users
;; to setup build directories, select build tool specific options and
;; manage configuration flags.

;;; Code:

(require 'transient)
(require 'cl-lib)
(require 'subr-x)

;;
;; Detection
;;

(defun hubi-configure--detect-system ()
  "Detect the build system used in the current project."
  (let ((root (condition-case nil (hubi--compile-root) (error nil))))
    (when root
      (cond
       ((file-exists-p (expand-file-name "configure" root)) 'configure)
       ((file-exists-p (expand-file-name "meson.build" root)) 'meson)
       ((file-exists-p (expand-file-name "CMakeLists.txt" root)) 'cmake)
       (t 'generic)))))

;;
;; Suffixes for Build Directory (Left Pane)
;;

(transient-define-suffix hubi-configure-new-dir ()
  "Create a new build directory."
  :description "New dir (builds/)"
  :transient t
  (interactive)
  (let* ((root (hubi--compile-root))
         (builds-dir (expand-file-name "builds/" root))
         (name (read-string "Build directory name: "))
         (new-dir (expand-file-name name builds-dir)))
    (unless (file-directory-p builds-dir)
      (make-directory builds-dir))
    (make-directory new-dir t)
    (setq hubi-directory new-dir)
    (message "Created and selected build directory: %s" new-dir)))

(transient-define-suffix hubi-configure-existing-dir ()
  "Select an existing build directory."
  :description "existing dir"
  :transient t
  (interactive)
  (call-interactively 'hubi-get-dir)
  (when (and hubi-directory (eq (hubi-configure--detect-system) 'configure))
    (let ((extracted (hubi-configure--extract-configure-args hubi-directory)))
      (setq hubi-configure-options extracted)
      (if extracted
          (message "Extracted options: %s" (mapconcat #'identity extracted " "))
        (message "No configuration found in %s, cleared options." hubi-directory)))))

;;
;; Heuristics to extract current configuration for a build dir
;; configured with a configure script. There are a large variety of
;; configure scripts but the most commons are:
;;
;;  - autoconf derived scripts
;;  - handwritten POSIX shell scripts
;;
;; config.status is generally an executable script which re-invokes
;; configure with additional arguments passed to it. Some like
;; autoconfig scripts will take arguments like --config to spit out
;; the config.
;;
;; exec '../../configure' '--disable-docs' '--disable-tools' '--extra-ldflags=-gsplit-dwarf' '--enable-debug-info' '--target-list=sh4-linux-user' "$@"
;;
;; config.log is usually the output of the running configure script
;; and will output something like (autoconf case):
;;
;;   It was created by git configure 2.26.0.103.g3bab5d5625, which was
;;   generated by GNU Autoconf 2.69.  Invocation command line was
;;     $ ./configure --prefix=/home/alex/src/git.git/install --no-create --no-recursion
;;
;; or as simple as a line like:
;;
;;   # Configured with: '../../configure' '--disable-docs' '--disable-tools' '--extra-ldflags=-gsplit-dwarf' '--enable-debug-info' '--target-list=sh4-linux-user'
;;

(defvar hubi-configure-options nil
  "List of currently set configuration options.")

(defcustom hubi-configure-extract-strategies
  '(hubi-configure--extract-from-autoconf-status
    hubi-configure--extract-from-generic-status
    hubi-configure--extract-from-config-log)
  "List of functions to try for extracting configuration arguments.
Each function takes one argument (the build directory) and should return
a string containing the configuration arguments, or nil if not found."
  :group 'hubi
  :type '(repeat function))

(defun hubi-configure--autoconf-config-status-p (status-path)
  "Return non-nil if STATUS-PATH is an autoconf config.status file."
  (when (file-exists-p status-path)
    (with-temp-buffer
      (insert-file-contents status-path)
      (string-match-p "Generated by .*Autoconf" (buffer-string)))))

(defun hubi-configure--extract-from-autoconf-status (dir)
  "Extract configure arguments from an autoconf config.status in DIR."
  (let ((config-status (expand-file-name "config.status" dir)))
    (when (hubi-configure--autoconf-config-status-p config-status)
      (with-temp-buffer
        (if (file-executable-p config-status)
            (ignore-errors (call-process config-status nil t nil "--config"))
          (insert-file-contents config-status))
        (if (re-search-forward "^ac_cs_config=['\"]\\(.*\\)['\"]\\s-*$" nil t)
            (match-string 1)
          (buffer-string))))))

(defun hubi-configure--extract-from-generic-status (dir)
  "Extract configure arguments from a generic config.status in DIR."
  (let ((config-status (expand-file-name "config.status" dir)))
    (when (file-exists-p config-status)
      (with-temp-buffer
        (insert-file-contents config-status)
        (goto-char (point-min))
        (when (re-search-forward "Invocation command line was\n\n[[:blank:]]*\\$ .*configure \\(.*\\)" nil t)
          (match-string 1))))))

(defun hubi-configure--extract-from-config-log (dir)
  "Extract configure arguments from a config.log in DIR."
  (let ((config-log (expand-file-name "config.log" dir)))
    (when (file-exists-p config-log)
      (with-temp-buffer
        (insert-file-contents config-log)
        (goto-char (point-min))
        (when (re-search-forward "^# Configured with: .*configure['\"]?\\s-+\\(.*\\)" nil t)
          (match-string 1))))))

(defvar hubi-configure--exec-match
  (rx
   line-start (zero-or-more blank)
   "exec" (one-or-more blank)
    "'" (zero-or-more (not "'")) "configure'"
    (one-or-more blank)
    (group (minimal-match (zero-or-more any)))
    (optional (seq (one-or-more blank) (or "\"$@\"" "$@")))
    (zero-or-more blank) line-end)
  "Regex to match `exec' invocations in config.status.")


(defun hubi-configure--clean-arg (arg)
  "Remove surrounding quotes from ARG."
  (setq arg (string-trim arg))
  (if (and (>= (length arg) 2)
           (or (and (string-prefix-p "'" arg) (string-suffix-p "'" arg))
               (and (string-prefix-p "\"" arg) (string-suffix-p "\"" arg))))
      (substring arg 1 -1)
    arg))

(defun hubi-configure--extract-configure-args (dir)
  "Attempt to extract configure arguments from DIR.
Iterates through `hubi-configure-extract-strategies' until a result is found."
  (let (args-str)
    (cl-loop for strategy in hubi-configure-extract-strategies
             until (setq args-str (funcall strategy dir)))
    (when (and args-str (not (string-empty-p args-str)))
      (let ((args (split-string-and-unquote args-str)))
        (cl-mapcan (lambda (s)
                     (let ((cleaned (hubi-configure--clean-arg s)))
                       (if (or (string-empty-p cleaned)
                               (string-match-p "configure$" cleaned))
                           nil
                         (list cleaned))))
                   args)))))

;;
;; Suffixes for Build Tool Actions (Middle Pane)
;;

;; Meson
(transient-define-suffix hubi-configure-meson-setup ()
  "Run meson setup."
  :description "configure"
  (interactive)
  (compile (hubi--format-configure "meson" hubi-directory hubi-configure-options hubi-env)))

(transient-define-suffix hubi-configure-meson-reconfigure ()
  "Run meson --reconfigure."
  :description "reconfigure"
  (interactive)
  (compile (format "meson --reconfigure %s" hubi-directory)))

;; Generic Configure
(transient-define-suffix hubi-configure-run-configure ()
  "Run the configure script."
  :description "run configure"
  (interactive)
  (compile (hubi--format-configure "configure" hubi-directory hubi-configure-options hubi-env)))

(transient-define-suffix hubi-configure-extract-configure ()
  "Run the configure script."
  :description "extract previous config"
  :transient t
  (interactive)
  (setq hubi-configure-options (hubi-configure--extract-configure-args hubi-directory)))

;;
;; Suffixes for Configure Options (Right Pane)
;;

(defun hubi-configure--get-configure-options ()
  "Parse the output of ./configure --help to find available options."
  (let* ((root (hubi--compile-root))
         (conf (expand-file-name "configure" root))
         (help-output (shell-command-to-string (format "%s --help" conf)))
         (options nil))
    (with-temp-buffer
      (insert help-output)
      (goto-char (point-min))
      ;; Look for lines starting with --[enable|disable|with|without]
      (while (re-search-forward "^[[:blank:]]*\\(--[[:alnum:]-]+\\)" nil t)
        (push (match-string 1) options)))
    (delete-dups (sort options #'string-lessp))))

(defun hubi-configure--get-meson-options ()
  "Use meson introspect to find available build options."
  (hubi--check-jq)
  (let* ((root (hubi--compile-root))
         (meson (hubi--find-meson-executable root)))
    (unless meson
      (setq meson (executable-find "meson")))
    (if meson
        (let* ((cmd (format "%s introspect --buildoptions %s | jq -r '.[] | \"-D\" + .name'"
                            (shell-quote-argument meson)
                            (shell-quote-argument root))))
          (split-string (shell-command-to-string cmd) "\n" t))
      nil)))

(defun hubi-configure--get-probed-options ()
  "Return a list of probed options for the current build system."
  (cond
   ((eq (hubi-configure--detect-system) 'configure) (hubi-configure--get-configure-options))
   ((eq (hubi-configure--detect-system) 'meson) (hubi-configure--get-meson-options))
   (t nil)))

(transient-define-suffix hubi-configure-add-option ()
  "Add a configuration option."
  :description "add option"
  :transient t
  (interactive)
  (let* ((probed (hubi-configure--get-probed-options))
         (opt (completing-read "Option: " probed)))
    (when (and opt (not (string-empty-p opt)))
      (push opt hubi-configure-options))))

(transient-define-suffix hubi-configure-remove-option ()
  "Remove a configuration option."
  :description "remove option"
  :transient t
  (interactive)
  (let ((opt (completing-read "Remove Option: " hubi-configure-options nil t)))
    (setq hubi-configure-options (delete opt hubi-configure-options))))

;;
;; The Main Configure Transient
;;

(defun hubi--configure-script-formatter (_cmd dir options &optional _env)
  "Format a standard configure script invocation for _CMD in DIR.
OPTIONS is a string of options and _ENV is the environment list."
  (let* ((root (hubi--compile-root))
         (conf (expand-file-name "configure" root)))
    (format "cd %s && %s %s" dir conf options)))

(defvar hubi--cfg-format-functions
  '(("configure" . hubi--configure-script-formatter)
    ("meson" . "meson setup %s %s")
    ("cmake" . "cmake -B %s %s")
    ("generic" . "unknown-configure %s"))
  "Alist of configure invocations and their format functions/strings.
The functions take (cmd dir options env) as arguments.
Format strings take (dir options) as arguments.")

(defun hubi--format-configure (cmd dir options &optional env)
  "Format a configuration string for CMD in DIR with OPTIONS.
Optional argument ENV is the environment list.
The formatter is looked up from `hubi--cfg-format-functions'."
  (let ((formatter (assoc-default cmd hubi--cfg-format-functions #'hubi--string-contains-p))
        (opt-str (if (listp options)
                     (mapconcat #'identity options " ")
                   options)))
    (cond
     ((functionp formatter)
      (funcall formatter cmd dir opt-str env))
     ((stringp formatter)
      (format formatter dir opt-str env))
     (t
      (format "no-configure-for-%s --dir %s %s" cmd dir opt-str)))))

(defun hubi--show-current-configure()
  "Return a Transient menu headline to indicate the current configuration command."
  (let* ((system (hubi-configure--detect-system))
         (cmd (symbol-name system)))
    (concat (propertize "Configure:\n  " 'face 'transient-heading)
            (propertize
             (hubi--format-configure
              cmd
              (or hubi-directory default-directory)
              hubi-configure-options
              hubi-env)
             'face 'transient-value)
            "\n")))

(defun hubi-configure--init ()
  "Initialize the configuration interface.
If `hubi-directory' is set but `hubi-configure-options' is not,
attempt to extract them."
  (when (and hubi-directory (not hubi-configure-options)
             (eq (hubi-configure--detect-system) 'configure))
    (setq hubi-configure-options (hubi-configure--extract-configure-args hubi-directory))))

;;;###autoload
(transient-define-prefix hubi-configure ()
  "Interface for configuring the project build."

  ["Configuration"
   :description hubi--show-current-configure

   ["Build Directory"
    ("n" hubi-configure-new-dir)
    ("d" hubi-configure-existing-dir)]

   ["Meson Options"
    :if (lambda () (eq (hubi-configure--detect-system) 'meson))
    ("c" hubi-configure-meson-setup)
    ("r" hubi-configure-meson-reconfigure)]

   ["Configure Options"
    :if (lambda () (eq (hubi-configure--detect-system) 'configure))
    ("c" hubi-configure-run-configure)
    ("x" hubi-configure-extract-configure)]

   ["Options"
    :description (lambda ()
                   (if hubi-configure-options
                       (let ((enabled-opts (mapconcat #'identity
                                                      hubi-configure-options " ")))
                         (format "Flags (%d): %s" (length hubi-configure-options)
                                 (if (> (length enabled-opts) 80)
                                     (concat (substring enabled-opts 0 80) "...")
                                   enabled-opts)))
                     "Flags: none"))
    ("a" hubi-configure-add-option)
    ("r" hubi-configure-remove-option)]]

  (interactive)
  (hubi-configure--init)
  (transient-setup 'hubi-configure))

(provide 'hubi-configure)
;;; hubi-configure.el ends here
