#+TITLE: Hubi To Do list

This isn't a comprehensive list but does track potential future improvements to the code.

* TODO hubi-configure

The main hubi interface is centred around building things. Usually these builds need configuring first.

I envision 3 panes in the transient interface. The left-most would be:

  Build Directory

    n - New dir (builds/)
    e - existing dir

Then next pane would be tool specific, so for example meson might offer:

  Meson Options
  
    c - configure
    r - reconfigure
    w - wipe build

We would need to use the same build system detection as well as look
for configure scripts (like QEMU uses to drive its meson config).
    
The final pane would list the configure options

 Configure Options

   --enable-foo --disable-baz --select=some,list,options

   a - add option
   r - remove options

The add option would be fed by history and possibly introspection into
the build system (parsing configure --help or meson's introspect
support or even looking at config.log or config.status)
   
* Addition Build System Support [0/1]
 - [ ] Evaluate CMake support - Currently supports Make, Ninja, Meson, Cargo.
 
